# Generated by Django 5.2.7 on 2025-10-23 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Kode unik voucher, misal: PROMOHEMAT20', max_length=50, unique=True)),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi singkat tentang voucher ini.')),
                ('persentase_diskon', models.DecimalField(decimal_places=2, help_text='Persentase diskon, misal: 15.50 untuk 15.5%', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Tandai jika voucher ini aktif dan bisa digunakan')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
            },
        ),
    ]
