# Generated by Django 5.2.5 on 2025-10-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(default='2025-10-24'),
        ),
    ]
