# Generated by Django 5.2.5 on 2025-10-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_voucher_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
