# Generated by Django 5.2.7 on 2025-10-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_alter_voucher_id'),
        ('voucher', '0003_alter_voucher_created_at'),
    ]

    operations = [
    ]
