# Generated by Django 5.2.7 on 2025-10-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_merge_20251024_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='created_at',
        ),
    ]
