# Generated by Django 5.2.5 on 2025-10-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_remove_voucher_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
