# Generated by Django 5.2.7 on 2025-10-24 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_brand'),
        ('voucher', '0005_remove_voucher_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_voucher_code', models.CharField(blank=True, help_text='Salinan kode voucher saat transaksi (untuk arsip)', max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('original_product_price', models.PositiveIntegerField(help_text='Harga produk saat dibeli')),
                ('applied_discount_percentage', models.PositiveIntegerField(default=0, help_text='Diskon yang didapat saat itu')),
                ('final_price', models.PositiveIntegerField(help_text='Harga final setelah diskon')),
                ('purchase_timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='voucher.voucher')),
            ],
            options={
                'ordering': ['-purchase_timestamp'],
            },
        ),
    ]
