# Generated by Django 5.2.7 on 2025-10-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
