# Generated by Django 5.2.7 on 2025-10-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createnews', '0002_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('event', 'Event'), ('training_tips', 'Training Tips'), ('sports_news', 'Sports News')], default='sports_news', max_length=20),
        ),
    ]
