# Generated by Django 5.2.7 on 2025-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createnews', '0003_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
