# Generated by Django 5.2.7 on 2025-10-22 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('waist', models.FloatField(blank=True, help_text='(Optional) Waist in centimeters', null=True)),
                ('hip', models.FloatField(blank=True, help_text='(Optional) Hip in centimeters', null=True)),
                ('chest', models.FloatField(blank=True, help_text='(Optional) Chest in centimeters', null=True)),
                ('recommended_size', models.CharField(max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
