# Generated by Django 5.2.7 on 2025-10-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMeasurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeasurement',
            name='recommended_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
