# Generated by Django 5.2.5 on 2025-10-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMeasurement', '0002_alter_usermeasurement_recommended_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermeasurement',
            old_name='recommended_size',
            new_name='clothes_size',
        ),
        migrations.AddField(
            model_name='usermeasurement',
            name='head_circumference',
            field=models.FloatField(default=55, help_text='Head circumference in centimeters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermeasurement',
            name='helmet_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
